"""This contains the knowledge base for testing on FOON dataset."""

GOALS = ['cut', 'stir', 'pour', 'wrap', 'heat', 'squeeze', 'sprinkle', 'roll', 'fry', 'dip', 'peel']

PLACES = ['dish', 'bowl', 'pot', 'plate', 'pan', 'tinfoil', 'cup', 'stove', 'baking dish',
          'paper towel',
          'skillet', 'mixing bowl', 'fruit bowl', 'bottle', 'rectangular plate', 'strainer', 'boiler', 'kettle',
          'grill', 'pitcher', 'teapot', 'cooker', 'frying pan', 'board', 'cooking pot', 'rectangular plate']

POUR_PLACES = ['bowl', 'pot', 'cup', 'bottle']

TOOLS = ['knife', 'colander', 'spoon', 'towel', 'tongs', 'pin',
         'fork', 'spatula', 'gloves', 'faucet', 'rolling pin',
         'toothpick', 'oven', 'olive oil', 'salt', 'white wine', 'pepper', 'milk', 'brush',
         'cutter', 'hand', 'mixer', 'microwave', 'scissors', 'toaster', 'tongs',
         'wine', 'squeezer', 'peeler']

OBJECTS = ['fruit mix', 'boiled eggs', 'cooked egg'] + ['beef', 'tortilla', 'lemon', 'chicken', 'onion',
                                                        'tomato', 'spice', 'mushroom', 'meat', 'garlic',
                                                        'tomato sauce', 'sauce', 'pasta', 'bacon', 'sausage', 'fish',
                                                        'cabbage', 'potato', 'butter', 'water', 'bread',
                                                        'flour', 'nutmeg', 'parsley', 'dough', 'black olive', 'olive',
                                                        'gyoza filling', 'patty', 'jelly', 'fruit', 'strawberry',
                                                        'pineapple',
                                                        'kiwi', 'orange', 'clams', 'cilantro', 'rice', 'celery',
                                                        'carrots', 'beef stock', 'sour cream', 'vegetables',
                                                        'green onion', 'bread crumbs', 'crumbs', 'wine',
                                                        'filling', 'stock', 'cream', 'oil', 'jelly roll',
                                                        'lemon juice', 'lemon sauce', 'milk mixture', 'broth',
                                                        'beef broth', 'lemon glaze', 'red pepper',
                                                        'jellyroll'] + ['escarole', 'albacore', 'alfredo sauce',
                                                                        'almond', 'anchovy', 'apple', 'apple cake',
                                                                        'arugula', 'mortar',
                                                                        'asparagus', 'avocado', 'bacon', 'bagel',
                                                                        'baguette', 'baking powder', 'baking soda',
                                                                        'banana', 'banana pudding',
                                                                        'banana pudding mix', 'barbecue sauce', 'basil',
                                                                        'basil mixture',
                                                                        'batter', 'bay leaf', 'beef', 'beef patty',
                                                                        'beef stew mix', 'beef stock',
                                                                        'beef stroganoff',
                                                                        'beefsteak', 'beer', 'beet', 'biscuit',
                                                                        'biscuit dough', 'black bean', 'black cherry',
                                                                        'black olive',
                                                                        'blackberry', 'blood orange',
                                                                        'blueberry', 'blueberry muffin', 'bologna',
                                                                        'bouillon',
                                                                        'bread', 'breadcrumbs', 'broccoli', 'broth',
                                                                        'brown rice', 'brown sugar', 'brownie',
                                                                        'brownie batter',
                                                                        'brussels sprouts', 'buckeye candy', 'bulgur',
                                                                        'bun', 'butter', 'buttermilk', 'cabbage',
                                                                        'caesar salad', 'cake', 'cake batter',
                                                                        'cake mix', 'calamari', 'candy', 'canola oil',
                                                                        'cantaloupe',
                                                                        'cappuccino', 'cardamom', 'carrot',
                                                                        'cauliflower', 'cayenne pepper', 'celery',
                                                                        'cereal',
                                                                        'chard',
                                                                        'cheese', 'cheese mixture', 'cheese sauce',
                                                                        'cherry', 'cherry tomato', 'chicken',
                                                                        'chicken broth',
                                                                        'chicken stock', 'chickpea', 'chili paste',
                                                                        'chili pepper', 'chili sauce', 'chipotle',
                                                                        'chipotle mix',
                                                                        'chipotle sauce', 'chive', 'chocolate',
                                                                        'chocolate bag', 'chocolate cake',
                                                                        'chocolate chip',
                                                                        'chocolate chip cookie',
                                                                        'chocolate chip muffin', 'chocolate mixture',
                                                                        'chocolate sandwich',
                                                                        'chorizo',
                                                                        'chutney', 'cider vinegar', 'cilantro',
                                                                        'cilantro-lime rice', 'cinnamon', 'clove',
                                                                        'club sandwich',
                                                                        'cocoa', 'cocoa bag', 'cocoa powder', 'coconut',
                                                                        'coconut milk', 'coconut milk powder',
                                                                        'coconut oil',
                                                                        'coconut water', 'coffee', 'coffee bean',
                                                                        'coffee filter', 'coffee maker',
                                                                        'coffee powder',
                                                                        'cognac',
                                                                        'coleslaw', 'condensed milk', 'cookie',
                                                                        'cookie dough', 'cooking spray', 'coriander',
                                                                        'corn',
                                                                        'corn flour', 'corn kernels', 'corn mixture',
                                                                        'corn starch', 'corn syrup', 'corned beef',
                                                                        'cornmeal',
                                                                        'couscous', 'crab', 'cranberry',
                                                                        'crayfish mixture', 'cream', 'cream cheese',
                                                                        'creamed corn',
                                                                        'croissant',
                                                                        'croquette', 'croquette mixture', 'crouton',
                                                                        'cucumber', 'cumin', 'curry', 'curry paste',
                                                                        'curry powder',
                                                                        'curry sauce', 'dark chocolate', 'dasheen',
                                                                        'dashi', 'dill', 'dough', 'drink',
                                                                        'dry mustard',
                                                                        'dumpling',
                                                                        'dumpling wrapper', 'edamame-mozzarella salad',
                                                                        'egg mixture', 'egg noodle',
                                                                        'egg white',
                                                                        'egg white and yolk', 'egg yolk', 'eggshell',
                                                                        'enchilada', 'enchilada sauce', 'feta cheese',
                                                                        'fettucini',
                                                                        'fig', 'fish mixture', 'fish sauce', 'flaxseed',
                                                                        'flour', 'flour glue', 'flour mixture',
                                                                        'french toast',
                                                                        'fried rice', 'fries', 'frittata', 'frosting',
                                                                        'fudge', 'fudge mixture', 'galangal',
                                                                        'garlic',
                                                                        'garlic bread',
                                                                        'garlic butter', 'garlic paste',
                                                                        'garlic powder', 'garlic rice', 'garlic salt',
                                                                        'garlic-parmesan chicken',
                                                                        'gelatin', 'gin', 'ginger', 'granola bar',
                                                                        'grape', 'grapefruit', 'grapeseed oil',
                                                                        'greek salad',
                                                                        'greek salad dressing', 'green bean',
                                                                        'green olive', 'green pea', 'green pepper',
                                                                        'greens',
                                                                        'ground beef',
                                                                        'ground pork', 'guacamole', 'gyoza',
                                                                        'gyoza filling',
                                                                        'ham', 'hamburger', 'hash brown', 'heavy cream',
                                                                        'honey', 'hot chocolate', 'hot dog',
                                                                        'hot sauce', 'ice',
                                                                        'ice cream', 'instant coffee',
                                                                        'italian sausage', 'italian seasoning',
                                                                        'jaggery', 'jalapeno',
                                                                        'jam',
                                                                        'jelly',
                                                                        'juice', 'kale', 'ketchup', 'kidney bean',
                                                                        'kiwi', 'kofta', 'kofta mix', 'kohlrabi',
                                                                        'lard',
                                                                        'leek',
                                                                        'lemon',
                                                                        'lemon extract', 'lemon grass', 'lemon juice',
                                                                        'lemon mixture', 'lemon zest', 'lemonade',
                                                                        'lentil',
                                                                        'lentil kofta',
                                                                        'lentil mix', 'lime', 'lime juice', 'lime zest',
                                                                        'linguine', 'liver', 'macaroni',
                                                                        'macaroni and cheese',
                                                                        'mackerel', 'mandarin', 'mango', 'maple syrup',
                                                                        'margarine', 'marinara', 'marmalade',
                                                                        'massaman curry',
                                                                        'matzo', 'matzo brei', 'matzo mixture',
                                                                        'matzo pancake', 'mayonnaise',
                                                                        'mayonnaise mixture',
                                                                        'meat mix',
                                                                        'milk', 'milk shake', 'mint', 'miso',
                                                                        'miso soup', 'mozzarella', 'muffin',
                                                                        'muffin batter',
                                                                        'mushroom',
                                                                        'mushroom soup', 'mustard', 'mustard seed',
                                                                        'naan', 'noodle', 'nutmeg', 'oats',
                                                                        'oil mixture', 'okra',
                                                                        'olive oil', 'omelette', 'onigiri', 'onion',
                                                                        'onion powder', 'orange', 'orange juice',
                                                                        'oregano',
                                                                        'oreo cookie',
                                                                        'oyster sauce', 'pancake', 'pancake batter',
                                                                        'pancake mix', 'paprika', 'parmesan', 'parsley',
                                                                        'pasta',
                                                                        'pasta alfredo',
                                                                        'pasta mix', 'patty', 'peach', 'peanut',
                                                                        'peanut brittle', 'peanut butter',
                                                                        'peanut mixture',
                                                                        'pear',
                                                                        'pecan',
                                                                        'penne', 'peppercorn', 'pepperoni', 'pesto',
                                                                        'pesto linguine', 'pickle', 'pico de gallo',
                                                                        'pigs in a blanket',
                                                                        'pine nut', 'pineapple', 'pistachio nut',
                                                                        'pita', 'pizza', 'plantain', 'plum',
                                                                        'pomegranate',
                                                                        'poppy seed',
                                                                        'porkchop', 'potato', 'potato chip',
                                                                        'potato mixture', 'potato salad',
                                                                        'powdered sugar',
                                                                        'pretzel',
                                                                        'protein powder',
                                                                        'protein shake', 'pudding', 'pudding mix',
                                                                        'pudding mixture', 'pulp', 'pumpkin',
                                                                        'quesadilla', 'radish',
                                                                        'raisin',
                                                                        'ramen', 'raspberry', 'red wine', 'relish',
                                                                        'ribs', 'rice', 'rice beer', 'rice mixture',
                                                                        'rose wine',
                                                                        'rosemary', 'roux', 'salad', 'salad dressing',
                                                                        'salad mix', 'salami', 'salmon', 'salsa',
                                                                        'salt',
                                                                        'saltwater',
                                                                        'sandwich', 'sardine', 'sauce', 'sausage',
                                                                        'scallion', 'scrambled eggs', 'sesame oil',
                                                                        'seaweed',
                                                                        'sesame seed',
                                                                        'shallot', 'shrimp', 'shrimp mango salad',
                                                                        'shrimp paste', 'skewer', 'smoothie', 'soup',
                                                                        'soup broth',
                                                                        'soup mix',
                                                                        'soup mix bag', 'soup stock', 'sour cream',
                                                                        'sourdough bread', 'soy mixture', 'soy sauce',
                                                                        'soybean',
                                                                        'spaghetti',
                                                                        'spaghetti sauce', 'spice', 'spice mixture',
                                                                        'spinach', 'spring mix', 'spring roll',
                                                                        'spring roll mix',
                                                                        'spring roll sheet', 'sprout',
                                                                        'stir-fried rice', 'strawberry', 'sugar',
                                                                        'sugar mixture',
                                                                        'sweet pepper',
                                                                        'sweet potato', 'sweet potato fries',
                                                                        'sweetener', 'taco seasoning', 'tangerine',
                                                                        'tarragon',
                                                                        'tea',
                                                                        'tea bag', 'tea leaf', 'tea mixture', 'thyme',
                                                                        'tofu', 'tomato', 'tomato paste',
                                                                        'tomato sauce',
                                                                        'tortilla', 'tuna', 'tuna paste', 'tuna patty',
                                                                        'tuna sandwich', 'tuna spread', 'turkey',
                                                                        'turmeric',
                                                                        'turnip', 'vanilla extract', 'vanilla wafer',
                                                                        'vegetable mix', 'vegetable oil',
                                                                        'vegetable stock',
                                                                        'vegetarian sausage', 'vermicelli',
                                                                        'vienna sausage', 'vinaigrette', 'vinegar',
                                                                        'waffle',
                                                                        'walnut',
                                                                        'water',
                                                                        'watercress', 'watermelon', 'whey',
                                                                        'whey powder', 'whipped cream',
                                                                        'whipping cream',
                                                                        'white chocolate chip',
                                                                        'white pepper', 'white rice', 'white sauce',
                                                                        'white wine', 'wonton', 'worcestershire sauce',
                                                                        'wrap',
                                                                        'yam',
                                                                        'yogurt', 'zucchini', 'egg']
OBJECTS = list(set(OBJECTS))

SPRINKLE_OBJECTS = ['spice', 'bacon', 'flour', 'parsley', 'nutmeg', 'basil', 'cheese', 'garlic']

SPRINKLE_TOOLS = ['salt', 'pepper']
